[package]
name = "ckb-analyzer"
version = "0.38.0"
license = "MIT"
authors = ["keroro <keroroxx520@gmail.com>"]
edition = "2018"
description = "ckb-analyzer analyzes kinds of data sources and upload the results into InfluxDB"
homepage = "https://github.com/keroro520/ckb-analyzer"

[dependencies]
ckb-suite-rpc = { path = "ckb-suite-rpc", version = "0.38.0" }
ckb-network = { version = "0.38.0" }
ckb-util = { version = "0.38.0" }
ckb-sync = { version = "0.38.0" }
ckb-logger = { version = "0.38.0" }
ckb-build-info = { version = "0.38.0" }
ckb-types = { version = "0.38.0" }
ckb-app-config = { version = "0.38.0" }

influxdb = { version = "0.3.0", features = ["derive"] }
tokio = { version = "0.2.22", features = ["full"] }
crossbeam = { version = "0.8.0" }
chrono = { version = "0.4.19" }
lazy_static = { version = "1.4.0" }
toml = { version = "0.5" }
gethostname = { version = "0.2.1" }
serde = { version = "1.0.117", features = [ "derive" ] }
serde_json = { version = "1.0.59" }
case_style = { version = "0.2.1" }
tynm = "0.1.6"
jsonrpc-core = "15.1"
jsonrpc-derive = "15.1"
jsonrpc-tcp-server = "15.1"
jsonrpc-ws-server = "15.1"
jsonrpc-server-utils = "15.1"
jsonrpc-pubsub = "15.1"
jsonrpc-core-client = "15.1"
jsonrpc-client-transports = "15.1"

[workspace]
members = [
    "ckb-suite-rpc"
]
