
[chain]
# default is false
enabled = true
ckb_url = "http://47.111.169.36:8121"

[network]
# default is false
enabled = false
ckb_network_name = "aggron" # "lina" | "aggron"
ckb_network_identifier = "/ckb_testnet/10639e08"

[topology]
# default is false
# enabled = false
ckb_urls = []


[influxdb]
database = "ckb"
url = "http://13.212.112.4:8086"
